config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "stocks#index"
  resources :users, only: [:edit, :update]
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :stocks, only: [:index, :new, :create, :edit, :update] do
    resources :purchases, only: [:new, :create]
    resources :orders, only: [:new, :create]
    collection do
      get 'search'
    end
  end
  resources :orders, only: [:index, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/code.rb
class Code < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '文学・小説' },
    { id: 3, name: '社会・ビジネス' },
    { id: 4, name: '旅行・地図' },
    { id: 5, name: '趣味' },
    { id: 6, name: '実用・教育' },
    { id: 7, name: 'アート・教育・エンタメ' },
    { id: 8, name: '辞典・図鑑・語学・辞書' },
    { id: 9, name: 'こども' },
    { id: 10, name: 'その他' }
  ]
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '新書' },
    { id: 3, name: '文庫' },
    { id: 4, name: '単行本' },
    { id: 5, name: 'その他' }
  ]
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :stock

  validates :quantity, presence: true
end

app/models/publisher.rb
class Publisher < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '講談社' },
    { id: 3, name: '集英社' },
    { id: 4, name: '角川書店' },
    { id: 5, name: '小学館' },
    { id: 6, name: '日経BP' },
    { id: 7, name: '宝島社' },
    { id: 8, name: '文芸春秋' },
    { id: 9, name: '東京書籍' },
    { id: 10, name: '光文社' },
    { id: 11, name: '新潮社' },
    { id: 12, name: '幻冬社' },
    { id: 13, name: '学研グループ' },
    { id: 14, name: 'NHK出版' },
    { id: 15, name: 'ダイヤモンド社' },
    { id: 16, name: '朝日新聞出版' },
    { id: 17, name: '岩波書店' },
    { id: 18, name: '医学書院' },
    { id: 19, name: 'ゼンリン' },
    { id: 20, name: 'ぎょうせい' },
    { id: 21, name: 'その他' }

  ]
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user
  belongs_to :stock

  validates :quantity, presence: true
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :user
  has_one :purchase
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :code
  belongs_to_active_hash :publisher
  belongs_to_active_hash :genre

  with_options presence: true do
    validates :number, :stock, numericality: { with: /\A[0-9]+\z/ }
    validates :code_id, :publisher_id, :genre_id, numericality: { other_than: 1 }
  end

  def self.search(search)
    if search != ''
      Stock.where('number LIKE(?) OR name LIKE(?) OR  author LIKE(?)', "%#{search}%", "%#{search}%", "%#{search}%")
    else
      Stock.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items
  has_many :purchases
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :authenticate_user! # ログイン画面へ遷移させる
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  # ユーザー認証
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  # nameカラムの保存を許可
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :setting, only: [:new, :create, :destroy]

  def index
    @orders = Order.order('created_at DESC')
  end

  def new
    @purchase = Purchase.new
  end

  def create
    @order = Order.create(order_params)
    if @order.save
      @stock.increment!(:stock, @order.quantity)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    binding.pry
    order = Order.find(params[:id])
    if order.destroy
      @stock.decrement!(:stock, order.quantity)
      redirect_to orders_path
    end
  end

  private

  def setting
    @stock = Stock.find(params[:stock_id])
  end

  def order_params
    params.permit(:quantity).merge(stock_id: params[:stock_id], user_id: current_user.id)
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :setting, only: [:new, :create]

  def new
    @purchase = Purchase.new
  end

  def create
    @purchase = Purchase.create(purchase_params)
    if @purchase.save && @stock.stock > 0
      @stock.decrement!(:stock, @purchase.quantity)
      redirect_to root_path
    elsif @purchase.quantity == 0
      render :new
    else
      render :new
    end
  end

  private

  def setting
    @stock = Stock.find(params[:stock_id])
  end

  def purchase_params
    params.permit(:quantity).merge(stock_id: params[:stock_id], user_id: current_user.id)
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def index
    @q = Stock.ransack(params[:q])
    @stocks = @q.result(distinct: true)
  end

  def new
    @stock = Stock.new
  end

  def create
    @stock = Stock.new(stock_params)
    if @stock.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @stock = Stock.find(params[:id])
  end

  def update
    @stock = Stock.find(params[:id])
    if @stock.update(stock_params)
      redirect_to root_path
    else
      render :edit
    end

  end

  def search
    @stocks = Stock.search(params[:keyword])
  end

  private

  def stock_params
    params.require(:stock).permit(:number, :name, :author, :stock, :genre_id, :code_id, :publisher_id).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params) # ユーザー情報を更新
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stock29839</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<div class="wrapper">
  <div class= "header-bar">
    <%= render "stocks/header_bar" %>
  </div>
   <div class="main-bar">
    <div class="stock-content">
      <div class="stock-name">
        <h1>発注履歴</h1>
      </div>
      </div>
      <table>
        <thead class="table-head">
          <tr>
            <th>商品番号</th>
            <th>商品名</th>
            <th>著者</th>
            <th>個数</th>
            <th>書籍分類</th>
            <th>ジャンル</th>
            <th>出版社</th>
            <th>発注者</th>
            <th>発注日時</th>
            <th></th>
          </tr>
        </thead>
          <% @orders.each do |order| %>
            <tbody class="table-body">
              <tr>
                <td><%= order.stock.number %></td>
                <td><%= order.stock.name %></td>
                <td><%= order.stock.author %></td>
                <td><%= order.quantity %></td>
                <td><%= order.stock.genre.name %></td>
                <td><%= order.stock.code.name %></td>
                <td><%= order.stock.publisher.name %></td>
                <td><%= order.user.name %></td>
                <td><%= order.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
                <td class="select-btn"><%= link_to '取消', order_path(order.id), method: :delete, class: "btn" %></td>
              </tr>
            </tbody>
          <% end %>
        </table>
    </div>
  </div>
</div>

app/views/orders/new.html.erb
  <div class= "header-bar">
    <%= render "stocks/header_bar" %>
  </div>
  <div class="contents row">
    <div class="container">
      <h3>発注する数</h3>
      <%= form_with model: @stocks, url:stock_orders_path, local: true do |form| %>
        <%= form.number_field :quantity, min: 1, class: "order-form" %>
        <%= form.submit "発注" %>
      <% end %>
    </div>
  </div>

app/views/purchases/new.html.erb
  <div class= "header-bar">
    <%= render "stocks/header_bar" %>
  </div>
  <div class="contents row">
    <div class="container">
      <h3>売った数</h3>
      <%= form_with model: @purchases, url:stock_purchases_path, local: true do |form| %>
        <%= form.number_field :quantity, min: 1, max: @stock.stock, class: "sell-form" %>
        <%= form.submit "売却" %>
      <% end %>
    </div>
  </div>

app/views/stocks/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
     <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/stocks/_header_bar.html.erb
<div class="header-left">
  <div class="header-name">
    <div class="icon">
      <h1>在庫管理</h1>
    </div>
  </div>
</div>

<div class="header-right">
  <ul class="header-menu">
    <li class="menu-list">
      <%= link_to "在庫一覧", root_path, class: 'btn'%>    
    </li>
    <li class="menu-list">
      <%= link_to "発注履歴", orders_path, class: 'btn'%>    
    </li>
    <li class="menu-list">
      <%= link_to "商品を追加", new_stock_path, class: 'btn' %>    
    </li>
     <li class="menu-list">
      <%= link_to current_user.name, edit_user_path(current_user), class: 'btn' %>      
    </li>
    <li class="menu-list">
      <%= link_to "ログアウト", destroy_user_session_path, class: 'btn'%>         
    </li>
  </ul>
</div>

app/views/stocks/_item.html.erb
<% @stocks.each do |stock| %>
            <tbody class="table-body">
              <tr>
                <td><%= stock.number %></td>
                <td><%= stock.name %></td>
                <td><%= stock.author %></td>
                <td><%= stock.stock %></td>
                <td><%= stock.genre.name %></td>
                <td><%= stock.code.name %></td>
                <td><%= stock.publisher.name %></td>
                <td class="select-btn"><%= link_to '編集', edit_stock_path(stock.id), class: "btn" %></td> 
                <td class="select-btn"><%= link_to '購入', new_stock_purchase_path(stock.id), class:"btn" %></td> 
                <td class="select-btn"><%= link_to '発注', new_stock_order_path(stock.id), class:"btn" %></td> 
              </tr>
            </tbody>
          <% end %>

app/views/stocks/edit.html.erb
<div class="wrapper">
  <div class= "header-bar">
    <%= render "stocks/header_bar" %>
  </div>
  <div class="contents row">
    <div class="container">
      <h1>商品を編集する</h1>
        <%= form_with model: @stock, url: stock_path, local: true do |f| %>
        <%= render 'error_messages', model: f.object %> 
        <div class="item-detail"> 
          <div class="form-name"> 
            商品番号
            <span class="dispensable">必須</span>
          </div>
          <%= f.text_field :number, placeholder: "商品番号" %>
          <div class="form-name"> 
            商品名
            <span class="dispensable">必須</span>
          </div>
          <%= f.text_field :name, placeholder: "商品名" %>
          <div class="form-name"> 
            著者
            <span class="dispensable">必須</span>
          </div>      
          <%= f.text_field :author, placeholder: "著者" %>
          <div class="form-name"> 
            個数
            <span class="dispensable">必須</span>
          </div>      
          <%= f.number_field :stock, placeholder: "個数", min: 0 %>
        </div>
        <div class="item-detail">
          <div class="form-name"> 
            種類
            <span class="dispensable">必須</span>
          </div>       
          <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box"}) %>
          <div class="form-name"> 
            ジャンル
            <span class="dispensable">必須</span>
          </div>      
          <%= f.collection_select(:code_id, Code.all, :id, :name, {}, {class:"select-box"}) %>
          <div class="form-name"> 
            出版社
            <span class="dispensable">必須</span>
          </div>      
          <%= f.collection_select(:publisher_id, Publisher.all, :id, :name, {}, {class:"select-box"}) %>
        </div>
        <%= f.submit "追加" %>
      <% end %>
    </div>
  </div>
</div>

app/views/stocks/index.html.erb
<div class="wrapper">
  <div class= "header-bar">
    <%= render "header_bar" %>
  </div>
  <div class="main-bar">
    <div class="stock-content">
      <div class="stock-name">
        <h1>在庫一覧</h1>
      </div>
      <div class="stock-search">
        <%= form_with url: search_stocks_path, local: true, method: :get, class: "search-form" do |form|  %>
          <%= form.text_field :keyword, placeholder: "在庫を検索する", class: "search-input" %>
          <%= form.submit "検索", class: "search-btn" %>
        <% end %>
      </div>
      <table>
        <thead class="table-head">
          <tr>
            <th><%= sort_link(@q, :number, "商品番号", class: "sort-btn") %></th>
            <th><%= sort_link(@q, :name, "商品名", class: "sort-btn") %></th>
            <th><%= sort_link(@q, :author, "著者", class: "sort-btn") %></th>
            <th><%= sort_link(@q, :stock, "個数", class: "sort-btn") %></th>
            <th><%= sort_link(@q, :genre_id, "種類", class: "sort-btn") %></th>
            <th><%= sort_link(@q, :code_id, "ジャンル", class: "sort-btn") %></th>
            <th><%= sort_link(@q, :publisher_id, "出版社", class: "sort-btn") %></th>
            <th class="select"></th>
            <th class="select"></th>
            <th class="select"></th>
          </tr>
        </thead>
          <%= render "item" %>
        </table>
    </div>
  </div>
</div>

app/views/stocks/new.html.erb
<div class="wrapper">
  <div class= "header-bar">
    <%= render "stocks/header_bar" %>
  </div>
  <div class="contents row">
    <div class="container">
      <h1>商品を追加する</h1>
        <div class="form">
        <%= form_with model: @stock, url: stocks_path, local: true do |f| %>
         <%= render 'error_messages', model: f.object %> 
        <div class="item-detail"> 
          <div class="form-name"> 
            商品番号
            <span class="dispensable">必須</span>
          </div>
          <%= f.text_field :number, placeholder: "商品番号" %>
          <div class="form-name"> 
            商品名
            <span class="dispensable">必須</span>
          </div>
          <%= f.text_field :name, placeholder: "商品名" %>
          <div class="form-name"> 
            著者
            <span class="dispensable">必須</span>
          </div>      
          <%= f.text_field :author, placeholder: "著者" %>
          <div class="form-name"> 
            個数
            <span class="dispensable">必須</span>
          </div>      
          <%= f.number_field :stock, placeholder: "個数", min: 0 %>
        </div>
        <div class="item-detail">
          <div class="form-name"> 
            種類
            <span class="dispensable">必須</span>
          </div>       
          <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box"}) %>
          <div class="form-name"> 
            ジャンル
            <span class="dispensable">必須</span>
          </div>      
          <%= f.collection_select(:code_id, Code.all, :id, :name, {}, {class:"select-box"}) %>
          <div class="form-name"> 
            出版社
            <span class="dispensable">必須</span>
          </div>      
          <%= f.collection_select(:publisher_id, Publisher.all, :id, :name, {}, {class:"select-box"}) %>
        </div>
        <%= f.submit "追加" %>
      <% end %>
    </div>
  </div>
</div>

app/views/stocks/search.html.erb
<div class="wrapper">
  <div class= "header-bar">
    <%= render "header_bar" %>
  </div>
  <div class="main-bar">
    <div class="stock-content">
      <div class="stock-name">
        <h1>商品在庫一覧</h1>
      </div>
      <div class="stock-search">
        <%= form_with  url: search_stocks_path, local: true, method: :get, class: "search-form" do |form|  %>
          <%= form.text_field :keyword, placeholder: "在庫を検索する", class: "search-input" %>
          <%= form.submit "検索", class: "search-btn" %>
        <% end %>
      </div>
      <table>
        <thead class="table-head">
          <tr>
            <th>商品番号</th>
            <th>商品名</th>
            <th>著者</th>
            <th>個数</th>
            <th>種類</th>
            <th>ジャンル</th>
            <th>出版社</th>
            <th class="select"></th>
            <th class="select"></th>
            <th class="select"></th>
          </tr>
        </thead>
         <%= render "item" %>
        </table>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "トップページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>